repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv
        args: ["run", "pylint"]
        language: system
        pass_filenames: true
        types: [python]